print("==========Country ame List===================")
print("Pakistan")
print("China")
print("United States of America")
print("India")
print("United Kingdom")
print("United states Emirates ")
print("Australia")
print("Iran")
print("Oman")
print("Afghanistan")
print("Russia")
print("Ukraine")
print("south Korea")
print("north Korea")
print("Argentina")
print("Sweden")
print("Switzerland")
print("England")
print("Finland")
print("France")
print("Germany")
print("Hungary")
print("italy")
print("spain")
print("japan === the country of rising sun ☀ ️")
print("Thailand")
print("Turkey")
